version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14 # or your desired node version
    commands:
      - echo Installing dependencies...
      - npm install express
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code...
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  discard-paths: no